import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import HomePage from './Home'
import { BrowserRouter,  Routes, Route } from "react-router-dom";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Learn Bands</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomePage />

    
    </div>
  )
}
